spring:
  datasource:
    url: jdbc:mysql://localhost:3306/globalmart_order_db?createDatabaseIfNotExist=true
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Consultant's Observability Strategy
management:
  endpoints:
    web:
      exposure:
        # Exposing 'refresh' is mandatory for @RefreshScope to work
        include: "health,info,refresh,beans"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Custom properties for our Business Logic
globalmart:
  environment: "Production-Simulation"
  order-prefix: "GM-ORD-"
